# ===============================================================
# PROJECT: Web Communication Using Chaotic Encryption with
#          Bijective Vector Addition Rules
# FILE   : receiver.py  (RECEIVER SIDE)
# ===============================================================

import numpy as np
import pickle
import os
import math
from PIL import Image

# ================= CONFIG =================
ENCRYPTED_FILE  = "encrypted_payload.npz"
SESSION_FILE    = "session_params.pkl"
KEY_FILE        = "key_matrix.pkl"
DECRYPTED_FILE  = "decrypted_image.png"
MOD             = 257
BLOCK_SIZE      = 9
MU              = 1.0
# ==========================================


# ──────────────────────────────────────────
# STEP 1 — LOAD KEY MATRIX
# ──────────────────────────────────────────
def load_key(mod=MOD) -> np.ndarray:
    """
    Loads the T matrix from key_matrix.pkl.
    This file was generated by sender.py and must be
    shared with the receiver via a secure channel.

    The T matrix is the root of all decryption:
      - Its trace seeds the 2D-LSCM chaotic sequence
      - T itself is used to recompute Ta and Tb
      - T^-1 is used in the inverse bijective mapping
    """
    print("\n[STEP 1] Loading Key Matrix...")
    if not os.path.exists(KEY_FILE):
        raise FileNotFoundError(
            f"Key file '{KEY_FILE}' not found!\n"
            "  Make sure key_matrix.pkl from the sender is in this folder."
        )
    with open(KEY_FILE, "rb") as f:
        T_matrix = pickle.load(f)

    if not (isinstance(T_matrix, np.ndarray) and T_matrix.shape == (9, 9)):
        raise ValueError("Invalid key file — expected 9x9 numpy array.")

    print(f"  T matrix loaded  : shape {T_matrix.shape}, mod {mod}")
    print(f"  Diagonal         : {np.diag(T_matrix)}")
    return T_matrix


# ──────────────────────────────────────────
# STEP 2 — LOAD ENCRYPTED PAYLOAD
# ──────────────────────────────────────────
def load_encrypted_payload():
    """
    Loads encrypted_payload.npz which contains:
      - cipher         : the encrypted + diffused 1D pixel array
      - original_shape : (H, W, 3) shape of the original image
    """
    print("\n[STEP 2] Loading Encrypted Payload...")
    if not os.path.exists(ENCRYPTED_FILE):
        raise FileNotFoundError(
            f"Encrypted file '{ENCRYPTED_FILE}' not found!\n"
            "  Run sender.py first to generate the encrypted payload."
        )
    data           = np.load(ENCRYPTED_FILE)
    cipher_data    = data["cipher"]
    original_shape = tuple(data["original_shape"])
    print(f"  Cipher length    : {len(cipher_data)}")
    print(f"  Original shape   : {original_shape}")
    return cipher_data, original_shape


# ──────────────────────────────────────────
# STEP 3 — LOAD SESSION PARAMS
# ──────────────────────────────────────────
def load_session_params():
    """
    Loads session_params.pkl which contains:
      - permutation : the index permutation applied during diffusion
      - xor_key     : the XOR key applied during diffusion

    Both were derived from the chaotic sequence on the sender side.
    To reverse diffusion, we need the inverse permutation and
    the same XOR key (XOR is its own inverse).
    """
    print("\n[STEP 3] Loading Session Parameters...")
    if not os.path.exists(SESSION_FILE):
        raise FileNotFoundError(
            f"Session file '{SESSION_FILE}' not found!\n"
            "  Make sure session_params.pkl from the sender is in this folder."
        )
    with open(SESSION_FILE, "rb") as f:
        permutation, xor_key = pickle.load(f)
    print(f"  XOR key          : {xor_key}")
    print(f"  Permutation len  : {len(permutation)}")
    return permutation, xor_key


# ──────────────────────────────────────────
# STEP 4 — REVERSE DIFFUSION LAYER
# ──────────────────────────────────────────
def reverse_diffusion(cipher_data, permutation, xor_key):
    """
    Reverses the secondary diffusion layer from sender Step 4.

    Sender applied:
      diffused = (cipher XOR xor_key)[permutation]

    To reverse:
      Step 1 — Compute inverse permutation
               inv_perm[permutation[i]] = i
      Step 2 — Apply inverse permutation to undo the shuffle
      Step 3 — XOR again with same key (XOR is its own inverse)
                 x XOR k XOR k = x
    """
    print("\n[STEP 4] Reversing Diffusion Layer...")

    # Inverse permutation
    inv_perm              = np.zeros_like(permutation)
    inv_perm[permutation] = np.arange(len(permutation))

    # Undo permutation, then undo XOR
    undiffused = (cipher_data[inv_perm]) ^ xor_key

    print(f"  Inverse permutation : applied")
    print(f"  XOR key reversed    : {xor_key}")
    return undiffused


# ──────────────────────────────────────────
# STEP 5 — 2D-LSCM CHAOTIC SEQUENCE
# ──────────────────────────────────────────
def generate_chaotic_sequence(T_matrix, length, mod=MOD):
    """
    Regenerates the exact same 2D-LSCM chaotic sequence
    that was used on the sender side.

    This works because:
      - Same T matrix → same trace(T) → same x0, y0 seeds
      - Same deterministic map formula → identical sequence

    2D-LSCM:
      x(n+1) = |sin(pi * mu * (y(n)+3) * x(n) * (1-x(n)))|
      y(n+1) = |sin(pi * mu * (x(n+1)+3) * y(n) * (1-y(n)))|
    """
    print("\n[STEP 5] Regenerating 2D-LSCM Chaotic Sequence...")

    trace_val = int(np.trace(T_matrix))
    x         = (trace_val % (mod - 1)) / mod
    y         = 1.0 - x

    print(f"  trace(T) = {trace_val}")
    print(f"  x seed   = {x:.6f}")
    print(f"  y seed   = {y:.6f}")

    chaos = []
    for _ in range(length):
        x = abs(math.sin(math.pi * MU * (y + 3) * x * (1 - x)))
        y = abs(math.sin(math.pi * MU * (x + 3) * y * (1 - y)))
        chaos.append((x + y) / 2.0)

    chaos_int = (np.array(chaos) * (mod - 1)).astype(int) % mod
    print(f"  Length   : {length}")
    print(f"  Sample   : {chaos_int[:5]}")
    return chaos_int


# ──────────────────────────────────────────
# MODULAR MATRIX INVERSE
# ──────────────────────────────────────────
def mod_matrix_inverse(T, mod=MOD):
    """
    Gauss-Jordan elimination in GF(mod).
    mod = 257 is prime → inverse always exists when diagonal != 0.
    """
    n   = T.shape[0]
    aug = np.hstack([T.astype(int) % mod, np.eye(n, dtype=int)])

    for col in range(n):
        pivot = int(aug[col, col]) % mod
        if pivot == 0:
            aug[col, col] = 1
            pivot         = 1
        p_inv    = pow(pivot, mod - 2, mod)
        aug[col] = (aug[col] * p_inv) % mod
        for row in range(n):
            if row != col:
                f        = int(aug[row, col]) % mod
                aug[row] = (aug[row] - f * aug[col]) % mod

    return aug[:, n:] % mod


# ──────────────────────────────────────────
# STEP 6 — INVERSE BIJECTIVE MAPPING
# ──────────────────────────────────────────
def bijective_decrypt(cipher_vector, chaotic_int, T_matrix, mod=MOD):
    """
    Reverses the bijective encryption formula.

    Sender applied:
      Q(a, b) = T^-1 (Ta + Tb)  mod 257

    To recover a (original pixels):
      T * Q = Ta + Tb          (multiply both sides by T)
      Ta    = T*Q - Tb         (subtract Tb)
      a     = T^-1 (T*Q - Tb)  (multiply by T^-1)

    So the inverse formula is:
      a = T^-1 ( T*Q - T*b )  mod 257
        = T^-1 * T * Q - b    mod 257
        = Q - b               mod 257

    Where:
      Q = encrypted block   (9 values)
      b = chaotic block     (9 values, same sequence as sender)
      T^-1 = modular inverse of T
    """
    print("\n[STEP 6] Inverse Bijective Mapping (Decryption)...")
    print("  Formula : a = T^-1(T*Q - T*b) mod 257")

    T_inv   = mod_matrix_inverse(T_matrix, mod)
    n       = len(cipher_vector)
    pad_len = (BLOCK_SIZE - n % BLOCK_SIZE) % BLOCK_SIZE
    q_pad   = np.pad(cipher_vector.astype(int), (0, pad_len))
    b_pad   = np.pad(chaotic_int,               (0, pad_len))
    output  = np.zeros(len(q_pad), dtype=int)

    for i in range(0, len(q_pad), BLOCK_SIZE):
        q_blk  = q_pad[i:i+BLOCK_SIZE]
        b_blk  = b_pad[i:i+BLOCK_SIZE]
        TQ     = (T_matrix @ q_blk) % mod
        Tb     = (T_matrix @ b_blk) % mod
        diff   = (TQ - Tb) % mod
        output[i:i+BLOCK_SIZE] = (T_inv @ diff) % mod

    recovered = output[:n].astype(np.uint8)
    print(f"  Decrypted (first 5) : {recovered[:5]}")
    return recovered


# ──────────────────────────────────────────
# STEP 7 — NPCR & UACI (VERIFICATION)
# ──────────────────────────────────────────
def compute_npcr_uaci(original, encrypted):
    """
    Computes NPCR and UACI between the encrypted image
    and the decrypted image.

    After correct decryption:
      NPCR should be ~0%   (decrypted == original → no pixels differ)
      UACI should be ~0%   (no intensity difference)

    This confirms the decryption was successful.
    """
    print("\n[STEP 7] NPCR & UACI Verification...")

    O    = original.astype(np.float64)
    E    = encrypted.astype(np.float64)

    npcr = (np.sum(O != E) / O.size) * 100.0
    uaci = (np.sum(np.abs(O - E) / 255.0) / O.size) * 100.0

    print(f"  NPCR (encrypted vs decrypted) : {npcr:.4f}%  (perfect = 0.0%)")
    print(f"  UACI (encrypted vs decrypted) : {uaci:.4f}%  (perfect = 0.0%)")

    if npcr == 0.0 and uaci == 0.0:
        print("  STATUS : PERFECT DECRYPTION — images are identical!")
    else:
        print("  STATUS : WARNING — decrypted image differs from original!")

    return npcr, uaci


# ──────────────────────────────────────────
# STEP 8 — SAVE DECRYPTED IMAGE
# ──────────────────────────────────────────
def save_decrypted_image(recovered_vector, original_shape):
    print("\n[STEP 8] Saving Decrypted Image...")
    img_array = recovered_vector.reshape(original_shape).astype(np.uint8)
    Image.fromarray(img_array, mode="RGB").save(DECRYPTED_FILE)
    print(f"  Saved : {DECRYPTED_FILE}")
    return img_array


# ──────────────────────────────────────────
# VISUALIZATION — DECRYPTION STEPS
# ──────────────────────────────────────────
def visualize_decryption(cipher_data, recovered_vector,
                         original_shape, npcr, uaci):
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import matplotlib.gridspec as gridspec

        fig = plt.figure(figsize=(22, 9), facecolor="#0d1117")
        fig.suptitle(
            "Chaotic Encryption — Decryption Steps Visualization",
            fontsize=14, fontweight="bold", color="#e6edf3", y=0.98
        )

        gs = gridspec.GridSpec(1, 4, figure=fig,
                               wspace=0.35,
                               left=0.04, right=0.97,
                               top=0.88, bottom=0.10)

        def styled_ax(loc, title):
            ax = fig.add_subplot(loc, facecolor="#161b22")
            ax.set_title(title, color="#58a6ff", fontsize=9,
                         fontfamily="monospace", pad=6)
            ax.tick_params(colors="#8b949e", labelsize=7)
            for sp in ax.spines.values():
                sp.set_edgecolor("#30363d")
            return ax

        # ── Panel 1: Encrypted image (input) ─────────────────
        ax1 = styled_ax(gs[0, 0], "INPUT — Encrypted Image (noise)")
        enc_img = cipher_data.reshape(original_shape).astype(np.uint8)
        ax1.imshow(enc_img)
        ax1.set_xlabel("Received encrypted payload", color="#8b949e", fontsize=7)
        ax1.axis("off")

        # ── Panel 2: Decrypted image ──────────────────────────
        ax2 = styled_ax(gs[0, 1], "OUTPUT — Decrypted Image")
        dec_img = recovered_vector.reshape(original_shape).astype(np.uint8)
        ax2.imshow(dec_img)
        ax2.set_xlabel("After inverse bijective + reverse diffusion",
                       color="#8b949e", fontsize=7)
        ax2.axis("off")

        # ── Panel 3: Difference map ───────────────────────────
        ax3 = styled_ax(gs[0, 2], "Difference Map (enc vs dec)")
        diff_map = np.abs(enc_img.astype(np.float64) -
                          dec_img.astype(np.float64)).astype(np.uint8)
        ax3.imshow(diff_map, cmap="hot")
        ax3.set_xlabel("Should appear nearly black if correct",
                       color="#8b949e", fontsize=7)
        ax3.axis("off")

        # ── Panel 4: NPCR & UACI verification bars ───────────
        ax4 = styled_ax(gs[0, 3], "Verification — NPCR & UACI")
        metrics    = ["NPCR (%)", "UACI (%)"]
        values     = [npcr, uaci]
        bar_colors = ["#39d353" if v == 0.0 else "#ff4444"
                      for v in values]
        bars = ax4.bar(metrics, values, color=bar_colors, width=0.4)
        ax4.axhline(0.0, color="#ffaa00", linestyle="--",
                    linewidth=1.2, label="Ideal = 0.0%")
        for bar, val in zip(bars, values):
            ax4.text(bar.get_x() + bar.get_width()/2,
                     max(bar.get_height(), 0.5),
                     f"{val:.4f}%", ha="center", va="bottom",
                     color="white", fontsize=8, fontweight="bold")
        ax4.set_ylim(0, max(max(values) * 1.3, 5))
        ax4.set_ylabel("Percentage (%)", color="#8b949e", fontsize=7)
        ax4.legend(fontsize=7, labelcolor="#8b949e",
                   facecolor="#161b22", edgecolor="#30363d")
        ax4.set_xlabel("Both should be 0.0% for perfect decryption",
                       color="#8b949e", fontsize=7)

        out_path = "decryption_visualization.png"
        plt.savefig(out_path, dpi=150, bbox_inches="tight",
                    facecolor="#0d1117")
        plt.close()
        print(f"\n  [VISUALIZATION] Saved: {out_path}")

    except ImportError:
        print("\n  [VISUALIZATION] Skipped — install matplotlib")
    except Exception as e:
        print(f"\n  [VISUALIZATION] Error: {e}")


# ──────────────────────────────────────────
# MAIN
# ──────────────────────────────────────────
def main():
    print("\n" + "="*60)
    print("  RECEIVER SIDE — CHAOTIC BIJECTIVE DECRYPTION SYSTEM")
    print("="*60)
    print("\n  Required files in this folder:")
    print(f"    1. {KEY_FILE}         <- T matrix from sender")
    print(f"    2. {ENCRYPTED_FILE}   <- encrypted data from sender")
    print(f"    3. {SESSION_FILE}     <- session params from sender")
    print("="*60)

    # STEP 1 — Load T matrix key
    T_matrix = load_key()

    # STEP 2 — Load encrypted payload
    cipher_data, original_shape = load_encrypted_payload()

    # STEP 3 — Load session params
    permutation, xor_key = load_session_params()

    # STEP 4 — Reverse diffusion (undo XOR + permutation)
    undiffused = reverse_diffusion(cipher_data, permutation, xor_key)

    # STEP 5 — Regenerate chaotic sequence
    chaotic_int = generate_chaotic_sequence(T_matrix, len(undiffused))

    # STEP 6 — Inverse bijective mapping
    recovered = bijective_decrypt(undiffused, chaotic_int, T_matrix)

    # STEP 7 — NPCR & UACI verification
    npcr, uaci = compute_npcr_uaci(cipher_data, recovered)

    # STEP 8 — Save decrypted image
    save_decrypted_image(recovered, original_shape)

    # VISUALIZATION
    visualize_decryption(cipher_data, recovered,
                         original_shape, npcr, uaci)

    print("\n" + "="*60)
    print("  DECRYPTION SUMMARY")
    print("="*60)
    print(f"  Cipher Length  : {len(cipher_data)} bytes")
    print(f"  Image Shape    : {original_shape}")
    print(f"  Chaotic Map    : 2D-LSCM (mu={MU})")
    print(f"  Block Size     : {BLOCK_SIZE}")
    print(f"  Modulus        : {MOD} (prime GF)")
    print(f"  T Matrix       : 9x9 upper triangular (loaded from key)")
    print(f"  NPCR           : {npcr:.4f}%  (perfect = 0.0%)")
    print(f"  UACI           : {uaci:.4f}%  (perfect = 0.0%)")
    print("="*60)
    print("\n  [SUCCESS] Decryption complete!")
    print(f"\n  Files generated:")
    print(f"    1. {DECRYPTED_FILE}")
    print(f"    2. decryption_visualization.png")
    print("="*60)


if __name__ == "__main__":
    main()